{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: autobuy-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  BITBANK_API_KEY: {{ .Values.bitbank.apiKey | quote }}
  BITBANK_API_SECRET: {{ .Values.bitbank.apiSecret | quote }}
{{- end }}
