on:
  push:
    tags:
    - 'v*'

name: Build and Release

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: takutakahashi/autobuy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag
        id: tag
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.SOURCE_TAG }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update chart appVersion
        run: sed -i "s/appVersion:.*/appVersion: \"${{ steps.tag.outputs.SOURCE_TAG }}\"/" charts/autobuy/Chart.yaml

      - name: Package and push Helm chart
        run: |
          helm package charts/autobuy
          helm push autobuy-*.tgz oci://ghcr.io/takutakahashi/charts
